### ISSUE TITLE
support mayavi build using vtk 6.2

### ISSUE THREAD

**Issue by itziakos** [enthought/mayavi#190]
When bulding mayavi on top of vtk 6.2 we get exceptions from the vtk_parser.

```python
$ python setup.py build
running build
----------------------------------------------------------------------
Building TVTK classes...
Traceback (most recent call last):
  File "setup.py", line 471, in <module>

  File "lib/python2.7/site-packages/numpy/distutils/core.py", line 169, in setup
    return old_setup(**new_attr)
  File "lib/python2.7/distutils/core.py", line 152, in setup
    dist.run_commands()
  File "/lib/python2.7/distutils/dist.py", line 953, in run_commands
    self.run_command(cmd)
  File "/lib/python2.7/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
  File "setup.py", line 303, in run

  File "setup.py", line 290, in build_tvtk_classes_zip

  File "tvtk/setup.py", line 62, in gen_tvtk_classes_zip
    # numpy.distutils does the Wrong(TM) thing.
  File "tvtk/code_gen.py", line 101, in generate_code
  File "tvtk/code_gen.py", line 191, in _write_wrapper_class
  File "tvtk/wrapper_gen.py", line 80, in generate_code
  File "tvtk/wrapper_gen.py", line 180, in _gen_methods
  File "tvtk/wrapper_gen.py", line 745, in _gen_other_methods
  File "tvtk/wrapper_gen.py", line 1046, in _write_tvtk_method
  File "tvtk/vtk_parser.py", line 309, in get_method_signature
AttributeError: 'NoneType' object has no attribute 'split'
```
I saw that it failed for when the method argument to get_method_signature was a type object.

**Comment by jenshnielsen** [comment]
I guess this could be the same issue as #159 ?

**Comment by itziakos** [comment]
True, the issues look similar and it might be they are cause by the same bug. @dmsurti we should investigate both.

**Comment by dmsurti** [comment]
@jenshnielsen @itziakos The issues are caused by the same underlying bug for VTK 6.2. This is due to changes in VTK api which need to be handled on the VTK parser that generates the TVTK bindings.

**Comment by dmsurti** [comment]
Fixed in #191
