### ISSUE TITLE
Scenes saving random desktop background images

### ISSUE THREAD

**Issue by ktavabi** [enthought/mayavi#631]
I am using `version 4.5.1.dev0` and the engine is consistently saving scenes as a file containing the image of the "random" application behind the TVTK scene at the time. For example if I try to save...
![image](https://user-images.githubusercontent.com/4381290/39210946-10ce6a16-47bf-11e8-834e-b9470a111942.png)
via `s.scene.save('test.png')` or `s.scene.save_png('test.png)` yields...
![image](https://user-images.githubusercontent.com/4381290/39211096-748c5658-47bf-11e8-80a0-a7b1a07f1e05.png)

I tried reproducing this with [an example ](http://docs.enthought.com/mayavi/mayavi/advanced_scripting.html) and 
`mayavi.new_scene() returned `
>AttributeError: module 'mayavi' has no attribute 'new_scene'

**Comment by prabhuramachandran** [comment]
version 4.5.1.dev0  is really a bogus number that isn't very helpful.  Are you using Mayavi from github master?  What version of VTK?

**Comment by ktavabi** [comment]
Just to be clear this issue is on a Linux Debian OS...I think the Universe might be trying to tell me something.
`mayavi(4.5.1.dev0)` and `vtk(8.1.0)` both installed using `pip` as per #598

**Comment by prabhuramachandran** [comment]
I suggest you use Mayavi from github master or wait a few weeks for a new pip installable release.  I am not sure about the messaging from the universe... 😀

**Comment by prabhuramachandran** [comment]
FWIW, I do have Mayavi working on Ubuntu 16.04 on a few machines.
