### ISSUE TITLE
Mayavi fails to build with python 3.10

### ISSUE THREAD

**Issue by opoplawski** [enthought/mayavi#1021]
From https://bugzilla.redhat.com/show_bug.cgi?id=1944533:

Mayavi fails to build with Python 3.10.0a6.
```
Building TVTK classes... 

Failed on ObjectBase
(#2 of 10 nodes, #62 of 111 subnodes)

Traceback (most recent call last):
  File "/builddir/build/BUILD/mayavi-4.7.2/setup.py", line 411, in <module>
    setup(
  File "/usr/lib64/python3.10/site-packages/numpy/distutils/core.py", line 169,
in setup
    return old_setup(**new_attr)
  File "/usr/lib/python3.10/site-packages/setuptools/__init__.py", line 153, in
setup
    return distutils.core.setup(**attrs)
  File "/usr/lib64/python3.10/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/usr/lib64/python3.10/distutils/dist.py", line 966, in run_commands
    self.run_command(cmd)
  File "/usr/lib64/python3.10/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/builddir/build/BUILD/mayavi-4.7.2/setup.py", line 268, in run
    build_tvtk_classes_zip()
  File "/builddir/build/BUILD/mayavi-4.7.2/setup.py", line 254, in
build_tvtk_classes_zip
    gen_tvtk_classes_zip()
  File "tvtk/setup.py", line 99, in gen_tvtk_classes_zip
    # become invalid.
  File "/builddir/build/BUILD/mayavi-4.7.2/tvtk/code_gen.py", line 134, in
generate_code
    self._write_wrapper_class(node, tvtk_name)
  File "/builddir/build/BUILD/mayavi-4.7.2/tvtk/code_gen.py", line 229, in
_write_wrapper_class
    self.wrap_gen.generate_code(node, out)
  File "/builddir/build/BUILD/mayavi-4.7.2/tvtk/wrapper_gen.py", line 256, in
generate_code
    self._gen_methods(node, out)
  File "/builddir/build/BUILD/mayavi-4.7.2/tvtk/wrapper_gen.py", line 355, in
_gen_methods
    self.parser.parse(klass)
  File "/builddir/build/BUILD/mayavi-4.7.2/tvtk/vtk_parser.py", line 156, in
parse
    self._organize_methods(klass, methods)
  File "/builddir/build/BUILD/mayavi-4.7.2/tvtk/vtk_parser.py", line 476, in
_organize_methods
    self.other_meths = [
  File "/builddir/build/BUILD/mayavi-4.7.2/tvtk/vtk_parser.py", line 478, in
<listcomp>
    if isinstance(getattr(klass, x), collections.Callable)
AttributeError: module 'collections' has no attribute 'Callable'
```
bpo-37324: Remove deprecated aliases to Collections Abstract Base Classes
from the collections module.

https://docs.python.org/3.10/whatsnew/changelog.html#python-3-10-0-alpha-6

For the build logs, see:
https://copr-be.cloud.fedoraproject.org/results/@python/python3.10/fedora-rawhide-x86_64/02108086-Mayavi/

For all our attempts to build Mayavi with Python 3.10, see:
https://copr.fedorainfracloud.org/coprs/g/python/python3.10/package/Mayavi/

Testing and mass rebuild of packages is happening in copr. You can follow these
instructions to test locally in mock if your package builds with Python 3.10:
https://copr.fedorainfracloud.org/coprs/g/python/python3.10/

Let us know here if you have any questions.

Python 3.10 will be included in Fedora 35. To make that update smoother, we're
building Fedora packages with early pre-releases of Python 3.10.
A build failure prevents us from testing all dependent packages (transitive
[Build]Requires), so if this package is required a lot, it's important for us
to get it fixed soon.
We'd appreciate help from the people who know this package best, but if you
don't want to work on this now, let us know so we can try to work around it on
our side.

**Comment by rahulporuri** [comment]
Thanks for the report @opoplawski .

**Comment by opoplawski** [comment]
Fedora Rawhide has now moved to python 3.10.0-beta2 and so Mayavi is failing to build.  Any chance this can be addressed soon?  Thanks.

**Comment by opoplawski** [comment]
Sorry for the delay, this seems to be working.  Thanks.
