### ISSUE TITLE
Error importing mlab

### ISSUE THREAD

**Issue by ipashchenko** [enthought/mayavi#1016]
```
Python 3.9.1
vtk==9.0.20210302
mayavi==4.7.3.dev0
```

``mayavi`` was installed as here #1015 (First, install`` VTK`` from github, then clone ``mayavi`` from github, remove ``vtk`` deps and install ``mayavi``). However, importing ``mlab`` results in error.
```
 In [2]: from mayavi import mlab
multiple 'pyface.toolkits' plugins found for toolkit 'qt4': pyface.ui.qt4.init, pyface.ui.qt4.init
multiple 'tvtk.toolkits' plugins found for toolkit 'qt4': tvtk.pyface.ui.qt4.init, tvtk.pyface.ui.qt4.init
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-2-67847bc6bfd0> in <module>
----> 1 from mayavi import mlab

~/github/mayavi/mayavi/mlab.py in <module>
     32 
     33 
---> 34 from .tools.helper_functions import contour3d, test_contour3d, \
     35     quiver3d, test_quiver3d, test_quiver3d_2d_data, \
     36     points3d, test_points3d, test_molecule, \

~/github/mayavi/mayavi/tools/helper_functions.py in <module>
     14 # License: BSD Style.
     15 
---> 16 from .modules import VectorsFactory, StreamlineFactory, GlyphFactory, \
     17             IsoSurfaceFactory, SurfaceFactory, ContourSurfaceFactory, \
     18             ImageActorFactory, ImagePlaneWidgetFactory, glyph_mode_dict

~/github/mayavi/mayavi/tools/modules.py in <module>
     25 from . import tools
     26 from .pipe_base import PipeFactory, make_function
---> 27 from .filters import new_class
     28 
     29 

~/github/mayavi/mayavi/tools/filters.py in <module>
     16 from tvtk.common import camel2enthought
     17 from tvtk.api import tvtk
---> 18 import mayavi.filters.api as filters
     19 from mayavi.core.registry import registry
     20 from .pipe_base import PipeFactory, make_function

~/github/mayavi/mayavi/filters/api.py in <module>
     17 from .elevation_filter import ElevationFilter
     18 from .extract_edges import ExtractEdges
---> 19 from .extract_grid import ExtractGrid
     20 from .extract_tensor_components import ExtractTensorComponents
     21 from .extract_unstructured_grid import ExtractUnstructuredGrid

~/github/mayavi/mayavi/filters/extract_grid.py in <module>
     13 
     14 from tvtk.api import tvtk
---> 15 from tvtk.vtk_module import VTK_MAJOR_VERSION
     16 
     17 # Local imports

ImportError: cannot import name 'VTK_MAJOR_VERSION' from 'tvtk.vtk_module' (/home/ilya/github/mayavi/tvtk/vtk_module.py)
```

**Comment by ipashchenko** [comment]
Manually adding  ``VTK_MAJOR_VERSION = 9`` to ``mayavi/tvtk/vtk_module.py`` file (as described in #939) fixed the issue. Simple plotting examples works.

**Comment by Scheiermann** [comment]
@ipashchenko Thanks, that helps.

In general I think that should be incorparated into a pull request.
@prabhuramachandran is there a possibility to automatically get the used vtk version here? Also in general there are a lot of steps to get mayavi working with python3.9 worked out by the community. Maybe it is time to get a official instruction guide how to set it up.
